version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes: 
      - db-data:/var/lib/mysql/data # named docker volume
  mongo-express:
    image: mongo-express
    ports:
      - 8080:8081
    environment:
      - ME_COFIG_MONGODB_ADMINUSERNAME=mongoadmin
      - ME_COFIG_MONGODB_ADMINPASSWORD=secret
      - ME_COFIG_MONGODB_SERVER=mongodb
volumes:
  db-data